version: '3'
services:
  front:
    image: node:12.7.0-alpine
    container_name: front
    working_dir: /home/node/front
    expose:
      - "3000"
    ports: 
      - 3000:3000
    volumes:
      - ./app/front:/home/node/front
    command: yarn run dev
