version: "3.7"
services:
  https-portal:
    image: steveltn/https-portal:1.14.0
    container_name: https-portal
    environment:
      HOST: 0.0.0.0
    ports:
      - 80:80
      - 443:443
    links:
      - front
      - api
    restart: always
    environment:
      DOMAINS: "sssignal.com -> http://front:3000, ver3.sssignal.com -> http://front:3000, api.sssignal.com -> http://api:1323"
      ERROR_LOG: stdout
      ACCESS_LOG: stderr
      STAGE: "production"

  front:
    build: ./app/front/
    container_name: front
    working_dir: /home/node/front
    environment:
      HOST: 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - ./app/front:/home/node/front
      - /home/node/front/node_modules
    command: ash -c "yarn run build && yarn run start"

  api:
    build: ./app/api/
    container_name: api
    working_dir: /go/cmd/sssignal3/app/api
    environment:
      HOST: 0.0.0.0
    ports:
      - 1323:1323
    links:
      - mongodb
    volumes:
      - ./:/go/cmd/sssignal3
    command: realize start --run --no-config

  cron:
    build: ./app/cron
    container_name: cron
    # コンテナを起動しっぱなしにする
    tty: true
    links:
      - mongodb
    volumes:
      - ./:/home/

  mongodb:
    image: mongo:4.2.2
    container_name: mongodb
    ports:
      - 27017:27017
    links:
      - front
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

volumes:
  mongodb-data:
    driver: local
