version: '3'
services:
  front:
    build: ./app/front/
    container_name: front
    working_dir: /home/node/front
    environment:
      HOST: 0.0.0.0
    ports: 
      - 3000:3000
    volumes:
      - ./app/front:/home/node/front
      - /home/node/front/node_modules
    command: yarn run dev
