# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # ssh
      - name: ssh sssignal3
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REPOSITORY_PATH: ${{ secrets.REPOSITORY_PATH }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > ssh_private_key
          chmod 600 ssh_private_key
          ssh -o StrictHostKeyChecking=no ${USER_NAME}@${SERVER_IP} -i ssh_private_key "cd $REPOSITORY_PATH && git pull origin master"
      # git checkout
      # docker-compose down
      # docker-compose up --build

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
